### ISSUE TITLE
Wrong energy consumption values

### ISSUE THREAD

**Issue by kpagnat** [chriscamicas/gazdebordeaux-ha#2]
Bonjour,

Tout d'abord, un grand merci pour le travail fourni pour cette intégration, ça m'a évité de parser le site de Gaz de Bordeaux et de créer mes propres API.

Lorsque je regarde les 3 capteurs fournis par l'intégration (Current energy usage, current bill gas usage & current bill gas cost), il semble que ceux-ci soient correctes par rapport à ce que je vois dans life.gazdebordeaux.fr.
Par contre, lorsque j'intégre le capteur "energy_consumption" dans le Dashboard Energy, cela me donne des valeurs complètement abhérentes, bien au delà des valeurs des capteurs.

Comment corriger ce problème ?

Merci par avance
Kevin

**Comment by chriscamicas** [comment]
Hello, merci beaucoup, j'avoue je viens de check chez moi c'est pareil...
Sincèrement, je n'utilise pas le dashboard Energy, j'ai eu des trucs bizarres avec, si tu te fais un dashboard à part avec les autres capteurs, c'est bon (ce que j'ai fait).
Je vais quand même creuser ça 👀

**Comment by kpagnat** [comment]
Merci pour le retour. Je trouve dommage de ne pas avoir tous mes suivis au même endroit. J'ai le suivi elec + production solaire dans le dashboard Energy et le suivi Gaz avec le coût était pratique également. Si ça se trouve ce n'est pas grand chose 😅
Bon courage

**Comment by chriscamicas** [comment]
Bon j'ai trouvé d'où ça vient et j'ai corrigé le problème
Il faut mettre à jour en 1.1.0 pour ne plus avoir le soucis.
Par contre, les valeurs passées erronées ne peuvent pas être corrigées automatiquement... 
Il y a 2 options

1. Supprimer, et remettre l'intégration
2. Stopper HA, Supprimer toutes les données en base, et redémarrer. Il considérera que c'est comme un premier setup et rechargera tout

Pour supprimer en DB, suivant la config, il faut passer par [l'add-on SQLite Web](https://community.home-assistant.io/t/home-assistant-community-add-on-sqlite-web/68912) (si tu utilises SQLite), et taper les 2 requêtes suivantes:
Trouver les id des statistiques
`SELECT * FROM "statistics_meta" where name like '%gaz%'`
<img width="1491" alt="image" src="https://github.com/chriscamicas/gazdebordeaux-ha/assets/7702519/bdda6044-f28d-4ba7-8443-093404c0853a">

et après supprimer toutes les stats pour les statistiques id correspondant à
`gazdebordeaux:energy_cost`
`gazdebordeaux:energy_consumption`
`gazdebordeaux:volume `

`DELETE  FROM "statistics" where (metadata_id = 64 OR metadata_id = 63 OR metadata_id = 62)`
<img width="1491" alt="image" src="https://github.com/chriscamicas/gazdebordeaux-ha/assets/7702519/251f51cb-28dd-4e2a-965c-eca504aee0ca">

**Comment by kpagnat** [comment]
Hello,

Je suis passé par les options 1 et 2 (j'aime bien repartir au propre) et ça roule nickel !
Merciiii

Bonne continuation
