### ISSUE TITLE
Régaz vs Gazdebordeaux

### ISSUE THREAD

**Issue by aqwserf** [chriscamicas/gazdebordeaux-ha#3]
Bonjour,
à mon tour d'avoir un compteur de gaz connecté ce mercredi :)

En lisant votre documentation, vous mentionnez https://life.gazdebordeaux.fr/. Or ce site n'est pas celui communiqué par l'installateur pour le suivi: https://monespace.regaz.fr.

Par ailleurs, le site life.gazdebordeaux.fr ne m'indique la consommation que jusqu'à février 2024, et celui de Regaz m'indique bien ma consommation jusqu'en juin, meme si je n'ai pas vérifié ces informations.

Qui a raison ? Faut-il adapter pour joindre regaz au lieu de life ou bien les informations de regaz vont être mises a jour sur life ?

Merci !

**Comment by chriscamicas** [comment]
Hello,
Très bonne question merci!
J'avais étudié les 2 API en effet, mais celle de regaz était pénible à utiliser pour les raisons suivantes:

- données à parser et à reformatter (number dans des strings entre autres)
- pas de possibilité de query avec un niveau de détail journalier sur plus d'un mois (=> ce qui implique de faire plusieurs requêtes). Les query month et year n'ont qu'une vue consolidée des données qui n'est pas utile pour HomeAssistant. On a besoin du détail jour, et tout le calcul est après fait par HA.
- le temps de réponse est pas ouf 2s environ pour les données d'1 mois... (sur life.gazdebordeaux ça répond en 300ms pour 6 mois de data)

life.gazdebordeaux.fr s'appuie sur les données regaz, donc il n'a pas plus ou moins raison, la source de vérité reste Regaz c'est les gestionnaires du compteur connecté. Leur API est juste moisie.

Peux-tu vérifier si tu as bien autorisé Regaz à transmettre tes données à life.gazdebordeaux.fr?
Il y a une option (opt-in) sur ton profil
<img width="913" alt="image" src="https://github.com/user-attachments/assets/32e03edd-3f29-48b2-a297-ebbae394f88a">

**Comment by chriscamicas** [comment]
<img width="1247" alt="image" src="https://github.com/user-attachments/assets/2eb9763b-d505-4da5-b704-7dab0d85c6d2">

**Comment by aqwserf** [comment]
Ok, ok, merci pour le retour rapide. Donc exit regaz :)
De mon côté, je n'ai pas cet onglet, même en forçant le paramètre `section`. Sûrement dû à l'installation récente.
![image](https://github.com/user-attachments/assets/59a59c68-a688-4097-a01d-eb1859abeda4)

Autre chose qui m'interroge, c'est la capacité de gazdebordeaux/regaz à me fournir des infos détaillées mois/mois alors même que je n'avais pas de compteur connecté (ici ca s’arrête a février mais j'ai les infos jusqu'en juin sur regaz):
![image](https://github.com/user-attachments/assets/1ada2c2b-fd0c-4e25-a95c-4ee65796103f)

**Comment by chriscamicas** [comment]
Alors là ... je n'en ai aucune idée désolé. Peut-être peux tu les contacter directement pour leur poser la question?
Si tu le fais, n'hésite pas à poster la réponse ici, ça m'intéresse et ça peut être utile pour d'autres personnes.
Merci

**Comment by chriscamicas** [comment]
Avec plaisir, si tu as des soucis ou des suggestions d'amélioration n'hésite pas !
Ça fait plaisir de voir qu'elle est utile à d'autres 😊
