### ISSUE TITLE
Could not authenticate

### ISSUE THREAD

**Issue by aqwserf** [chriscamicas/gazdebordeaux-ha#7]
Hi,
since yesterday, the integration no longer works with this error message:
```
Config entry '(xxxxxx)' for gazdebordeaux integration could not authenticate: 500, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://life.gazdebordeaux.fr/api/login_check'
```

My login/password are correct as I'm able to login to https://life.gazdebordeaux.fr.

Trying to reload the integration does not work either.

However, I noticed a change in the https://life.gazdebordeaux.fr UI (colors, Co2, badges...). Maybe a change on their side?

Also, I only have results for Monday/Tuesday this week:
![image](https://github.com/user-attachments/assets/f28d5a15-f9fc-42be-b872-33a9c2622e32)

Thanks!

**Comment by chriscamicas** [comment]
Hello, je confirme j'ai bien le même problème de mon côté ... je regarde

**Comment by chriscamicas** [comment]
tu peux mettre à jour l'intégration c'est fix ;)

**Comment by aqwserf** [comment]
quelle rapidité :) je test ça rapidement

as-tu aussi des données non remontées pour mercredi/jeudi cette semaine ?

**Comment by nyok92** [comment]
bonjour @chriscamicas Peux tu faire une release 1.1.3 ? Pour qu'on puisse mettre  à jour avec HACS ? Merci ! :)

HACS ne propose pas la branche main

**Comment by chriscamicas** [comment]
> quelle rapidité :) je test ça rapidement
> 
> as-tu aussi des données non remontées pour mercredi/jeudi cette semaine ?

oui leur API ne remonte rien pour ces jours (pour le moment)...

**Comment by chriscamicas** [comment]
> bonjour @chriscamicas Peux tu faire une release 1.1.3 ? Pour qu'on puisse mettre à jour avec HACS ? Merci ! :)
> 
> HACS ne propose pas la branche main

bien vu, c'est fait !

**Comment by aqwserf** [comment]
Tout fonctionne. Merci !
